server:
  port: 8080

spring:
  application:
    name: transfer-service
  kafka:
    state:
      dir: /tmp/kafka-streams/bank
    producer:
      bootstrap-servers: localhost:29092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer